In [1]:
def homework(*messages):
    print(" >> ", " ".join(str(message) for message in messages))
import numpy as np
import os

In [2]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0]).reshape(l)
print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / (C + 1)}  # Уникнення ділення на 0
Степінь:\n {C ** Z}
Порівняння:\n {R > 0.5}
Ділення на 0 (замість цього уникаємо ділення на 0):\n {np.divide(O, Z, out=np.full_like(O, np.inf), where=Z!=0)}
""")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.91332473 0.26128917 0.35157287]
 [0.847404   0.95592338 0.95052303]
 [0.68008323 0.88135735 0.08046401]]
Ділення:
 [[       inf 0.26128917 0.17578644]
 [       inf 0.95592338 0.47526152]
 [       inf 0.88135735 0.040232  ]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Порівняння:
 [[ True False False]
 [ True  True  True]
 [ True  True False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [3]:
homework("Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.")
K = np.eye(6)
homework(K == 1)
ones = np.ones((6, 6))
homework(ones - K)

 >>  Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
 >>  [[ True False False False False False]
 [False  True False False False False]
 [False False  True False False False]
 [False False False  True False False]
 [False False False False  True False]
 [False False False False False  True]]
 >>  [[0. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 0.]]


In [4]:
A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
