In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")

import numpy as np

In [2]:
C = np.array([[0.7543, 0.2432, 0.6741, 0.8125],
              [0.9423, 0.1234, 0.5768, 0.6791],
              [0.3456, 0.8765, 0.4321, 0.5432]])

print(f"""АНАЛОГОВ НЄТ: Масив {C.shape} можна задавати вручну:
{C}
""")

rng = np.random.default_rng()
C = rng.random((3, 4))
print(f"""АНАЛОГОВ НЄТ: Можна згенерувати випадковий масив такої ж розмірності {C.shape}:
{C}
""")

rng = np.random.default_rng(seed=42)
C = rng.random((3, 4))
print(f"""АНАЛОГОВ НЄТ: Для того щоб згенерований масив {C.shape} мав завжди однакові значення, використовуємо параметр seed:
{C}
""")

I = rng.integers(0, 15, size=(3, 4), endpoint=True)
print(f"""АНАЛОГОВ НЄТ: Можемо оперувати цілими числами (задаючи мін і макс):
{I}
""")


АНАЛОГОВ НЄТ: Масив (3, 4) можна задавати вручну:
[[0.7543 0.2432 0.6741 0.8125]
 [0.9423 0.1234 0.5768 0.6791]
 [0.3456 0.8765 0.4321 0.5432]]

АНАЛОГОВ НЄТ: Можна згенерувати випадковий масив такої ж розмірності (3, 4):
[[0.9024013  0.67216322 0.44791665 0.81680572]
 [0.96626829 0.36135692 0.22852361 0.47712346]
 [0.96440102 0.93288855 0.08071095 0.54251182]]

АНАЛОГОВ НЄТ: Для того щоб згенерований масив (3, 4) мав завжди однакові значення, використовуємо параметр seed:
[[0.77395605 0.43887844 0.85859792 0.69736803]
 [0.09417735 0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802 0.92676499]]

АНАЛОГОВ НЄТ: Можемо оперувати цілими числами (задаючи мін і макс):
[[12 10  6 13]
 [ 8  7  7  3]
 [ 1  8 14  1]]



In [3]:
C = np.array([3, 7, 11, 13, 17, 19]) 
print(f"""АНАЛОГОВ НЄТ: Працюємо з останнім масивом:
{C}

Сума всіх елементів:    {C.sum()}
Добуток всіх елементів: {C.prod()}

Мінімальний елемент:    {C.min()}
Максимальний елемент:   {C.max()}

Середнє значення:       {C.mean()}  \tте саме що {C.sum() / np.size(C)}
Медіана:                {np.median(C)}      
Дисперсія:              {C.var()}   \tте саме що {np.sum((C - C.mean())**2 / C.size)}
Відхилення:             {C.std()}   \tте саме що {np.sqrt(C.var())}

Заокруглили всі значення:
{np.round(C)}
Та знайшли унікальні величини: {np.unique(np.round(C))}
Та порахували кількість унікальних значень: {np.unique(np.round(C), return_counts=True)[1]}
""")


АНАЛОГОВ НЄТ: Працюємо з останнім масивом:
[ 3  7 11 13 17 19]

Сума всіх елементів:    70
Добуток всіх елементів: 969969

Мінімальний елемент:    3
Максимальний елемент:   19

Середнє значення:       11.666666666666666  	те саме що 11.666666666666666
Медіана:                12.0      
Дисперсія:              30.222222222222218   	те саме що 30.22222222222222
Відхилення:             5.497474167490214   	те саме що 5.497474167490214

Заокруглили всі значення:
[ 3  7 11 13 17 19]
Та знайшли унікальні величини: [ 3  7 11 13 17 19]
Та порахували кількість унікальних значень: [1 1 1 1 1 1]



In [4]:
C = C.reshape(2, 3)
print(f"""АНАЛОГОВ НЄТ: {C}

Сума елементів по стовпцях:         {C.sum(axis=0)}
Сума елементів по рядках:           {C.sum(axis=1)}

Добуток елементів по стовпцях:      {C.prod(axis=0)}
Добуток елементів по рядках:        {C.prod(axis=1)}

Мінімальний елемент по стовпцях:    {C.min(axis=0)}
Мінімальний елемент по рядках:      {C.min(axis=1)}
Максимальний елемент по стовпцях:   {C.max(axis=0)}
Максимальний елемент по рядках:     {C.max(axis=1)}

Середнє значення по стовпцях:       {C.mean(axis=0)}
Дисперсія по стовпцях:              {C.var(axis=0)}
Відхилення по стовпцях:             {C.std(axis=0)}

""")


АНАЛОГОВ НЄТ: [[ 3  7 11]
 [13 17 19]]

Сума елементів по стовпцях:         [16 24 30]
Сума елементів по рядках:           [21 49]

Добуток елементів по стовпцях:      [ 39 119 209]
Добуток елементів по рядках:        [ 231 4199]

Мінімальний елемент по стовпцях:    [ 3  7 11]
Мінімальний елемент по рядках:      [ 3 13]
Максимальний елемент по стовпцях:   [13 17 19]
Максимальний елемент по рядках:     [11 19]

Середнє значення по стовпцях:       [ 8. 12. 15.]
Дисперсія по стовпцях:              [25. 25. 16.]
Відхилення по стовпцях:             [5. 5. 4.]


